config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  namespace :api do
    namespace :v1 do
      resources :offers
    end
  end
  resources :home, only: [:index, :create]
  resources :category_offer, only: [:index, :show]
  namespace :account do
    resources :profile, only: [:index]
    resources :offer
  end
  devise_for :users,
    :controllers => {:registrations => "registrations"}
  match '/users', to: 'home#index', via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :subcategories, class_name: "Category", foreign_key: "parent_id", dependent: :destroy
  belongs_to :parent_category, class_name: "Category", optional: true
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_one_attached :cover_picture

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :profile_picture
  has_many :offers
end

app/controllers/account/offer_controller.rb
class Account::OfferController < AccountController
  before_action :offer_form, only: [:new, :create]
  before_action :load_offer, only: [:edit, :show, :update]

  def index
    @offers = policy_scope(Offer).page(params[:page])
  end

    def show
    end

    def new
    end

    def edit
      @offer_form    = Offer.find_by_id(params[:id])
      authorize @offer_form
      @category_name = Category.find_by_id(@offer_form.category_id).name
    end

    def update
      authorize @offer
      @offer_form ||= @offer_form = OfferForm.new(@offer)
      if form_validate
        @offer.update(offer_params_update)
        flash[:success] = 'Votre annonce a bien été mis à jour'
        redirect_to account_offer_path(@offer_form.id)
      else
        flash[:error] = 'Erreur de validation'
        render :edit
      end
    end

    def destroy
      offer = Offer.find_by_id(params[:id])
      offer.destroy if offer.user_id == current_user.id
      flash[:success] = 'Votre annonce a été supprimé'
      redirect_to account_offer_index_path
    end

    def create
      if form_validate
        @offer_form.save
        flash[:success] = 'Votre annonce a été créé'
        redirect_to account_offer_path(@offer_form.id)
      else
        flash[:error] = 'Erreur de validation'
        render :new
      end
    end

    private

    def offer_form
      offer = Offer.new \
        user_id:  current_user&.id
      @offer_form ||= OfferForm.new(offer)
    end

    def offer_params_update
      param = params.require(:offer).permit(:title, :price, :description, :category_id, :cover_picture, :location)
      param[:category_id] = @offer_form.category_id
      param
    end

    def offer_params
      params.require(:offer).permit(:title, :price, :description, :category_id, :cover_picture, :location)
    end

    def form_validate
      @offer_form.validate offer_params
    end

    def load_offer
      @offer = Offer.find_by_id(params[:id])
    end

  end

app/controllers/account/profile_controller.rb
class Account::ProfileController < AccountController

  def index
  end

end

app/controllers/account_controller.rb
class AccountController < ApplicationController
  layout :determine_layout
  before_action :check_authentication

  private

  def check_authentication
    redirect_to root_path unless current_user \
      || controller_name == "offer" \
      || controller_name == "category_offer" && params[:action] == "index"
    if current_user.nil? && controller_name == "offer" && ["edit", "index"].include?(params[:action])
      flash[:error] = "vous n'avez rien à faire ici"
      redirect_to root_path
    end
  end

  def determine_layout
    controller_name == "offer" && current_user.nil? ? "home_unlogged" : "home"
  end
end

app/controllers/api/v1/offers_controller.rb
module Api
  module V1
    class OffersController < ApplicationController
      def index
        category = Category.find_by_name(params[:category])
        if category.nil?
          render json: { error: true, message: "Aucune categorie trouvé" }
          return false
        end
        offers_count = Offer.where(category_id: category.id).count
        render json: {error: false, offers: offers_count}
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  before_action :store_location

  def store_location
    unless params[:controller] == "devise/sessions"
      session[:user_return_to]        = params[:controller]
      session[:user_return_to_action] = params[:action]
    end
  end

  before_action do
    I18n.locale = :fr
  end

  rescue_from Pundit::NotAuthorizedError do
    flash[:error] = "Vous n'avez pas accès à cette page."
    redirect_to root_path
  end

  def after_sign_in_path_for(resource)
    if session[:user_return_to] == "account/offer"
      new_account_offer_path
    else
      root_path
    end
  end
end

app/controllers/category_offer_controller.rb
class CategoryOfferController < ApplicationController
  layout :determine_layout
  before_action :load_offers, only: [:show]

  def index
    @offers = OrderedOffersSearchQuery.new(search_params).call.page(params[:page])
  end

  def show
  end

  private

  def load_offers
    @category = Category.find_by_id(params[:id])
    if @category.nil?
      @offers = []
    else
      @offers = Offer.where(category_id: @category.id).page(params[:page])
    end
  end

  def search_params
    params.permit(:category, :location_search, :text_search)
  end

  def determine_layout
    current_user.nil? ? "home_unlogged" : "home"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :search_params, only: [:create]

  layout :determine_layout

  def index
    @categories = Category.where(parent_id: nil)
  end

  def create
    redirect_to category_offer_index_path(
      category:     @params[:category_id],
      text_search:  @params[:text_search],
      location_search: @params[:location_search])
  end

  private

  def determine_layout
    current_user ? "home" : "home_unlogged"
  end

  def search_params
    @params = params.require(:search).permit(:text_search, :location_search, :category_id)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  layout "home"

  def new
    super
  end

  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      render :new
    end
  end

  def update
    super
  end

  private

  def sign_up_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/category_offer/index.html.slim
.container
  br
  h4
    = "Liste de vos annonces:"
  - if @offers.empty?
    .card style=("width: 58rem;")
      .card-body
        h5.card-title
          | Aucune annonce trouvé
  - @offers.each do |offer|
    .card style=("width: 58rem;")
      = link_to image_tag(offer.cover_picture, style: "height:100px;width:600px"), account_offer_path(offer)
      .card-body
        h5.card-title
          = "Categorie: #{offer.category.name}"
        h5.card-title
          = "Titre: #{offer.title}"
        h6.card-subtitle.mb-2.text-muted
          = "Prix: #{offer.price} €"
        p.card-text
          = offer.description
        div
          a.content
            i.fas.fa-eye
            | &nbsp
            = link_to 'Voir l\'annonce',
              account_offer_path(offer.id)
    br
  - unless @offers.empty?
    = paginate @offers

app/views/category_offer/show.html.slim
.container
  br
  h4
    = "Liste de vos annonces: #{@category&.name}"
  - if @offers.empty?
    .card style=("width: 58rem;")
      .card-body
        h5.card-title
          | Catégorie non trouvé
  - @offers.each do |offer|
    .card style=("width: 58rem;")
      = link_to image_tag(offer.cover_picture, style: "height:100px;width:600px"), account_offer_path(offer)
      .card-body
        h5.card-title
          = "Categorie: #{offer.category.name}"
        h5.card-title
          = "Titre: #{offer.title}"
        h6.card-subtitle.mb-2.text-muted
          = "Prix: #{offer.price} €"
        p.card-text
          = offer.description
        div
          a.content
            i.fas.fa-eye
            | &nbsp
            = link_to 'Voir l\'annonce',
              account_offer_path(offer.id)
          | &nbsp;
          - if policy(offer).edit?
            a.content
              i.fas.fa-edit
              | &nbsp
              = link_to 'Editer l\'annonce',
                edit_account_offer_path(id: offer.id)
          | &nbsp;
          - if policy(offer).edit?
            a.content
              i.fas.fa-trash-alt
              | &nbsp
              = link_to 'Supprimer l\'annonce',
                account_offer_path(id: offer.id),
                method: :delete,
                data: { confirm: 'Etes vous sure?'  }
    br
  - unless @offers.empty?
    = paginate @offers

app/views/home/index.html.slim
.container
  .card-deck.mb-3.text-center
    h4
      | Avec la livraison chez vous en point relais
       tout est à portée de main !
    p
      | Trouvez la bonne affaire parmi les millions de petites annonces leboncoin

.container
  .card.text-center
    .card-header
      ul.nav.nav-tabs.card-header-tabs
        li.nav-item
          a.nav-link.active href="#"  Offres
        li.nav-item
          a.nav-link href="#" Demande
    .card-body
      nav.navbar.navbar-light.bg-light.navbar-expand-sm.mb-3
        button.navbar-toggler data-target=".navbar-collapse" data-toggle="collapse" type="button"
          span.navbar-toggler-icon
        .collapse.navbar-collapse
          ul.navbar-nav.mr-auto
            li.nav-item.dropdown
              a.nav-link.dropdown-toggle id="main-field-dropdown" data-submenu="" data-toggle="dropdown"
                i.fas.fa-list
                | &nbsp
                | Catégories
              .dropdown-menu id="dropdown-toggle"
                - @categories.each do |category|
                  .dropdown.dropright.dropdown-submenu
                    button.dropdown-item.dropdown-toggle id="category_#{category.id}"
                      = category.name
                    .dropdown-menu
                      - category.subcategories.each do |sub_category|
                        button.dropdown-item type="button" id="category_#{category.id}"
                          = sub_category.name
                  .dropdown.dropright.dropdown-submenu id="dropdown-toggle"
        .container id="search_data"
          | &nbsp
          | &nbsp
          i.fas.fa-search
          | &nbsp
          input.form-control id="text_search_origin" aria-describedby="basic-addon1" aria-label="Username" placeholder="Que recherchez-vous ?" type="text"
          | &nbsp
          i.fas.fa-map-marker
          | &nbsp
          input.form-control id="location_search_origin" aria-describedby="basic-addon1" aria-label="Username" placeholder="Saisissez une ville" type="text"

      = simple_form_for :search, url: home_index_path do |f|
        = f.input :text_search, as: :hidden, input_html: {id: "text_search"}
        = f.input :location_search, as: :hidden, input_html: {id: "location_search"}
        = f.input :category_id, as: :hidden, input_html: {id: "category_id"}
        = f.button :submit, "Rechercher (#{Offer.all.count} résultats)", class: "btn btn-primary", id: "submit_button"

app/views/layouts/application.html.slim
doctype html
html
  head
    title Leboncoin
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    #main-container
      = render "layouts/home/navbar"
      = yield
      br style="line-height:100px;"
      = render "layouts/home/footer"

app/views/layouts/home.html.slim
doctype html
html
  head
    title Leboncoin
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    #main-container
      = render "layouts/home/navbar"
      = flash_messages
      = yield
      br style="line-height:100px;"
      = render "layouts/home/footer"

app/views/layouts/home/_navbar.html.slim
nav.navbar.navbar-expand-md.navbar-dark.bg-dark
  .navbar-collapse.collapse.w-100.order-1.order-md-0.dual-collapse2
    ul.navbar-nav.mr-auto
      li.nav-item.active
        = link_to "Leboncoin", root_path, class: "nav-link"
      li.nav-item
        = link_to new_account_offer_path, class: "btn btn-warning" do
          i.fas.fa-plus-square
          | &nbsp
          | Déposer une annonce
      li.nav-item
        a.nav-link href="/"
          i.fa.fa-search
          | &nbsp
          | Rechercher
          span.sr-only (current)
  .navbar-collapse.collapse.w-100.order-3.dual-collapse2
    ul.navbar-nav.ml-auto
      li.nav-item
        a.nav-link href="#"
          i.fa.fa-bell
          | &nbsp
          | Mes recherches
          span.sr-only (current)
      li.nav-item
        a.nav-link href="#"
          i.fa.fa-bookmark
          | &nbsp
          | Favoris
          span.sr-only (current)
      li.nav-item
        a.nav-link href="#"
          i.fas.fa-envelope
          | &nbsp
          | Messages
          span.sr-only (current)
      li.nav-item
        = link_to "Mon compte", account_profile_index_path, class: "btn btn-light"

app/views/layouts/home_unlogged.html.slim
doctype html
html
  head
    title Leboncoin
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  body
    #main-container
      = render "layouts/home_unlogged/navbar"
      = yield
      br style="line-height:100px;"
      = render "layouts/home_unlogged/footer"

app/views/layouts/home_unlogged/_footer.html.slim
.container
  footer.pt-4.my-md-5.pt-md-5.border-top
    .row
      .col-12.col-md
        img.mb-2 alt="" height="24" src="https://gw.alipayobjects.com/zos/antfincdn/4zAaozCvUH/unexpand.svg" width="24" /
        small.d-block.mb-3.text-muted &copy; 2019-2020
      .col-6.col-md
        h5 À propos du boncoin
        ul.list-unstyled.text-small
          li
            a.text-muted href="#" Qui sommes-nous ?
          li
            a.text-muted href="#" Nous rejoindre
          li
            a.text-muted href="#" Acteur responsable de l’économie française
      .col-6.col-md
        h5 Informations Légales
        ul.list-unstyled.text-small
          li
            a.text-muted href="#" Conditions générales d’utilisation
          li
            a.text-muted href="#" Règles de diffusion, de référencement et de déréférencement
          li
            a.text-muted href="#" Conditions Générales de Vente
          li
            a.text-muted href="#" Vie privée / cookies
      .col-6.col-md
        h5 Des questions ?
        ul.list-unstyled.text-small
          li
            a.text-muted href="#" Aide
          li
            a.text-muted href="#" Le service de paiement sécurisé et la livraison
          li
            a.text-muted href="#" Demandez conseil à la Communauté

app/views/layouts/home_unlogged/_navbar.html.slim
nav.navbar.navbar-expand-md.navbar-dark.bg-dark
  .navbar-collapse.collapse.w-100.order-1.order-md-0.dual-collapse2
    ul.navbar-nav.mr-auto
      li.nav-item.active
				= link_to "Leboncoin", root_path, class: "nav-link"
      li.nav-item
        = link_to new_account_offer_path, class: "btn btn-warning" do
          i.fas.fa-plus-square
          | &nbsp
          | Déposer une annonce
      li.nav-item
				a.nav-link href="/"
					i.fa.fa-search
					| &nbsp
					| Rechercher
					span.sr-only (current)
  .navbar-collapse.collapse.w-100.order-3.dual-collapse2
    ul.navbar-nav.ml-auto
			li.nav-item
				a.nav-link href="#"
					i.fa.fa-bell
					| &nbsp
					| Mes recherches
					span.sr-only (current)
			li.nav-item
				a.nav-link href="#"
					i.fa.fa-bookmark
					| &nbsp
					| Favoris
					span.sr-only (current)
			li.nav-item
				a.nav-link href="#"
					i.fas.fa-envelope
					| &nbsp
					| Messages
					span.sr-only (current)
			li.nav-item
				= link_to "Se connecter", new_user_session_path, class: "btn btn-light"